"""Descrição da mudança

Revision ID: 6695a3c14ea4
Revises: 896384bd4c76
Create Date: 2024-08-25 01:44:48.520135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import reflection


# revision identifiers, used by Alembic.
revision = '6695a3c14ea4'
down_revision = '896384bd4c76'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = reflection.Inspector.from_engine(bind)
    # ### commands auto generated by Alembic - please adjust! ###
    if 'pessoa' not in inspector.get_table_names(schema='farmzul'):
        op.create_table('pessoa',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.Text(), nullable=False),
        sa.Column('data_nascimento', sa.Date(), nullable=False),
        sa.Column('cpf', sa.String(length=11), nullable=False),
        sa.Column('genero', sa.String(length=25), nullable=True),
        sa.Column('telefone', sa.String(length=11), nullable=True),
        sa.Column('email', sa.String(length=100), nullable=True),
        sa.Column('endereco', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('cpf'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('telefone'),
        schema='farmzul'
        )
    
    if 'funcionario' not in inspector.get_table_names(schema='farmzul'):
        op.create_table('funcionario',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('id_pessoa', sa.Integer(), nullable=True),
        sa.Column('data_admissao', sa.Date(), nullable=False),
        sa.Column('cargo', sa.String(length=25), nullable=False),
        sa.Column('salario', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('data_demissao', sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(['id_pessoa'], ['farmzul.pessoa.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='farmzul'
        )

    if 'usuario' not in inspector.get_table_names(schema='farmzul'):
        op.create_table('usuario',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('id_funcionario', sa.Integer(), nullable=True),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('senha', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(['id_funcionario'], ['farmzul.funcionario.id'], ),
        sa.PrimaryKeyConstraint('id'),
        schema='farmzul'
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario', schema='farmzul')
    op.drop_table('funcionario', schema='farmzul')
    op.drop_table('pessoa', schema='farmzul')
    # ### end Alembic commands ###
