"""tbl func

Revision ID: bc52f063556c
Revises: 02c6dfbb2f84
Create Date: 2024-08-25 01:19:24.567172

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.engine import reflection


# revision identifiers, used by Alembic.
revision = 'bc52f063556c'
down_revision = '02c6dfbb2f84'
branch_labels = None
depends_on = None


def upgrade():
    # Create an engine to inspect the existing tables
    bind = op.get_bind()
    inspector = reflection.Inspector.from_engine(bind)

    # Check if the table already exists
    if 'pessoa' not in inspector.get_table_names(schema='farmzul'):
        op.create_table(
            'pessoa',
            sa.Column('id', sa.Integer, primary_key=True),
            sa.Column('nome', sa.String(length=255), nullable=False),
            sa.Column('data_nascimento', sa.Date, nullable=False),
            sa.Column('cpf', sa.String(length=11), nullable=False, unique=True),
            sa.Column('genero', sa.String(length=25)),
            sa.Column('telefone', sa.String(length=11), unique=True),
            sa.Column('email', sa.String(length=100), unique=True),
            sa.Column('endereco', sa.String(length=255)),
            schema='farmzul'
        )
    


    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('pessoa',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('nome', sa.Text(), nullable=False),
    # sa.Column('data_nascimento', sa.Date(), nullable=False),
    # sa.Column('cpf', sa.String(length=11), nullable=False),
    # sa.Column('genero', sa.String(length=25), nullable=True),
    # sa.Column('telefone', sa.String(length=11), nullable=True),
    # sa.Column('email', sa.String(length=100), nullable=True),
    # sa.Column('endereco', sa.Text(), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('cpf'),
    # sa.UniqueConstraint('email'),
    # sa.UniqueConstraint('telefone'),
    # schema='farmzul'
    # )
    op.create_table('funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pessoa', sa.Integer(), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=False),
    sa.Column('cargo', sa.String(length=25), nullable=False),
    sa.Column('salario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_demissao', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_pessoa'], ['farmzul.pessoa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='farmzul'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funcionario', schema='farmzul')
    op.drop_table('pessoa', schema='farmzul')
    # ### end Alembic commands ###
