"""coluna nova usuario

Revision ID: e585aca831e2
Revises: 417bcc6c4c97
Create Date: 2024-08-27 23:05:40.948334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e585aca831e2'
down_revision = '417bcc6c4c97'
branch_labels = None
depends_on = None


def upgrade():

    op.add_column('usuario', sa.Column('permissao', sa.String(length=15), nullable=True), schema='farmzul')

    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('pessoa',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('nome', sa.Text(), nullable=False),
    # sa.Column('data_nascimento', sa.Date(), nullable=False),
    # sa.Column('cpf', sa.String(length=11), nullable=False),
    # sa.Column('genero', sa.String(length=25), nullable=True),
    # sa.Column('telefone', sa.String(length=11), nullable=True),
    # sa.Column('email', sa.String(length=100), nullable=True),
    # sa.Column('endereco', sa.Text(), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('cpf'),
    # sa.UniqueConstraint('email'),
    # sa.UniqueConstraint('telefone'),
    # schema='farmzul'
    # )
    # op.create_table('funcionario',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('id_pessoa', sa.Integer(), nullable=True),
    # sa.Column('data_admissao', sa.Date(), nullable=False),
    # sa.Column('cargo', sa.String(length=25), nullable=False),
    # sa.Column('salario', sa.Numeric(precision=10, scale=2), nullable=False),
    # sa.Column('data_demissao', sa.Date(), nullable=True),
    # sa.ForeignKeyConstraint(['id_pessoa'], ['farmzul.pessoa.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # schema='farmzul'
    # )
    # op.create_table('usuario',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('id_funcionario', sa.Integer(), nullable=True),
    # sa.Column('username', sa.String(length=50), nullable=False),
    # sa.Column('senha', sa.String(), nullable=False),
    # sa.Column('permissao', sa.String(length=15), nullable=False),
    # sa.ForeignKeyConstraint(['id_funcionario'], ['farmzul.funcionario.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # schema='farmzul'
    # )
    # op.create_table('administrador',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('id_usuario', sa.Integer(), nullable=True),
    # sa.Column('permissao_adicional', sa.String(length=50), nullable=False),
    # sa.Column('responsavel_por_departamento', sa.String(length=50), nullable=False),
    # sa.ForeignKeyConstraint(['id_usuario'], ['farmzul.usuario.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # schema='farmzul'
    # )
    # op.create_table('operador',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('id_usuario', sa.Integer(), nullable=True),
    # sa.Column('area_operacao', sa.String(length=50), nullable=False),
    # sa.Column('supervisor_direto', sa.String(length=50), nullable=True),
    # sa.ForeignKeyConstraint(['id_usuario'], ['farmzul.usuario.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # schema='farmzul'
    # )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operador', schema='farmzul')
    op.drop_table('administrador', schema='farmzul')
    op.drop_table('usuario', schema='farmzul')
    op.drop_table('funcionario', schema='farmzul')
    op.drop_table('pessoa', schema='farmzul')
    # ### end Alembic commands ###
